/*Vocab defaults
 * 
 * These are just the initial defaults when the app is started for the first time.
 * To add or edit vocabularies, use the 'vocab' service provided by app_mongo.js
 * 
 * (This would be more pleasing as a 'proper' json file, but would require 
 *  reformatting and parsing)
 * 
 * */

module.exports = {

    defaultVocabs: function () {
        return     [ { type : 'colours',
                      permisssions : 'default',
                      items : [
                          {name: 'black', secondaryname:'sort', grp:''},
                          {name: 'blue', secondaryname:'blå', grp:''},
                          {name: 'brown', secondaryname:'brun', grp:''},
                          {name: 'green', secondaryname:'grøn', grp:''},
                          {name: 'grey', secondaryname:'grå', grp:''},
                          {name: 'orange', secondaryname:'orange', grp:''},
                          {name: 'purple', secondaryname:'lilla', grp:''},
                          {name: 'red', secondaryname:'rød', grp:''},
                          {name: 'white', secondaryname:'hvid', grp:''},
                          {name: 'yellow', secondaryname:'gul', grp:''}
                      ]
                    },
                    { type : 'pigments',
                      permisssions : 'default',
                      items : [
                          {grp:'', name:'zinc white', secondaryname:'zinkhvid'},
                          {grp:'', name:'calcium sulfate', secondaryname:'kalciumsulfat'},
                          {grp:'', name:'lead grey', secondaryname:'blygrå'},
                          {grp:'', name:'lead white', secondaryname:'blyhvid'},
                          {grp:'', name:'minium', secondaryname:'mønje'},
                          {grp:'', name:'permanent red', secondaryname:'permanentrød'},
                          {grp:'', name:'vermilion', secondaryname:'cinnober'},
                          {grp:'', name:'lacker yellow', secondaryname:'lakgul'},
                          {grp:'', name:'zinc chromate', secondaryname:'zinkchromat, zinc yellow, zinkgul'},
                          {grp:'', name:'chrome yellow', secondaryname:'chromgul'},
                          {grp:'', name:'yellow from palermo', secondaryname:'gul fra palermo'},
                          {grp:'', name:'lemon yellow', secondaryname:'ultramarine yellow, ultramaringul'},
                          {grp:'', name:'Indian yellow', secondaryname:'indisk gul'},
                          {grp:'', name:'Neapel yellow', secondaryname:'neapelgul '},
                          {grp:'', name:'cadmium yellow', secondaryname:'cadmiumgul'},
                          {grp:'', name:'organic yellow', secondaryname:'organisk gul'},
                          {grp:'', name:'glaze yellow', secondaryname:'lasurgul'},
                          {grp:'', name:'cadmiumorange', secondaryname:'cadmiumorange'},
                          {grp:'', name:'yellow', secondaryname:'gul'},
                          {grp:'', name:'cadmium', secondaryname:'cadmium'},
                          {grp:'', name:'green earth', secondaryname:'grønjord'},
                          {grp:'', name:'turmeric', secondaryname:'gurkemeje'},
                          {grp:'', name:'ocher', secondaryname:'okker'},
                          {grp:'', name:'burnt ocher', secondaryname:'brændt okker'},
                          {grp:'', name:'sienna', secondaryname:'siena'},
                          {grp:'', name:'earth brown', secondaryname:'jordbrun'},
                          {grp:'', name:'iron laquer', secondaryname:'jernlak'},
                          {grp:'', name:'umber', secondaryname:'umbra'},
                          {grp:'', name:'burnt green earth', secondaryname:'burnt terre verte, brændt grønjord, verona brun'},
                          {grp:'', name:'aniline yellow', secondaryname:'anilingul'},
                          {grp:'', name:'mummy', secondaryname:'mumiin'},
                          {grp:'', name:'red lead', secondaryname:'jernmønje'},
                          {grp:'', name:'Empire red', secondaryname:'kejserrød'},
                          {grp:'', name:'red ocher', secondaryname:'dodenkop, caput mortuum'},
                          {grp:'', name:'iron oxide red', secondaryname:'jernoxidrød, light red, English red'},
                          {grp:'', name:'Venetian red', secondaryname:'venetiansk rød'},
                          {grp:'', name:'aniline red', secondaryname:'anilinrød'},
                          {grp:'', name:'Mars violet', secondaryname:'marsviolet'},
                          {grp:'', name:'burnt umber', secondaryname:'iron oxide brown, jernoxidbrun, brændt umbra'},
                          {grp:'', name:'ivory black', secondaryname:''},
                          {grp:'', name:'asphalt', secondaryname:'asfalt '},
                          {grp:'', name:'Vandyke brown', secondaryname:'Cassel earth, kasselerbrun, Cologne earth, kølnerbrunt'},
                          {grp:'', name:'pearl red', secondaryname:'perlerød'},
                          {grp:'', name:'chrome red', secondaryname:'chromrød'},
                          {grp:'', name:'cochineal', secondaryname:'cochenille, Florentine lake, florentinerlak'},
                          {grp:'', name:'madder', secondaryname:'alizarin, kraplak'},
                          {grp:'', name:'cadmium red', secondaryname:'cadmiumrød'},
                          {grp:'', name:'carmine lake', secondaryname:'karmin'},
                          {grp:'', name:'Berlin red', secondaryname:'berlinerrød'},
                          {grp:'', name:'litmus', secondaryname:'lakmus'},
                          {grp:'', name:'hematite', secondaryname:'hæmatit, blodsten'},
                          {grp:'', name:'aniline blue', secondaryname:'anlilinblå'},
                          {grp:'', name:'cobalt violet', secondaryname:'koboltviolet'},
                          {grp:'', name:'cobalt green', secondaryname:'koboltgrøn, zinc green, zinkgrøn'},
                          {grp:'', name:'emerald green', secondaryname:'smaragdgrøn'},
                          {grp:'', name:'chromium oxide green', secondaryname:'chromoxidgrøn, ultramarine green, ultramaringrøn, bronzegrøn'},
                          {grp:'', name:'chrome oxide', secondaryname:'chromoxid, kromilte'},
                          {grp:'', name:'wagon green', secondaryname:'vogngrøn'},
                          {grp:'', name:'verdigris', secondaryname:'spansk grøn'},
                          {grp:'', name:'malachite green', secondaryname:'malakitgrøn, Victoria green, viktoriagrøn'},
                          {grp:'', name:'brilliant green', secondaryname:'brilliant grøn'},
                          {grp:'', name:'permanent green', secondaryname:'permanentgrøn'},
                          {grp:'', name:'lokao', secondaryname:'Chinese green, Kinesisk oliegrøn'},
                          {grp:'', name:'chrome green', secondaryname:'green vermilion, cinnobergrøn, chromgrøn'},
                          {grp:'', name:'smalt', secondaryname:'smalte'},
                          {grp:'', name:'azurite', secondaryname:'azurit, bjergblå'},
                          {grp:'', name:'blue verditer', secondaryname:'bremerblå'},
                          {grp:'', name:'indigo', secondaryname:'indigo'},
                          {grp:'', name:'Milori blue', secondaryname:'miloriblå'},
                          {grp:'', name:'azure blue', secondaryname:'azurblå'},
                          {grp:'', name:'ultramarine', secondaryname:'ultramarin'},
                          {grp:'', name:'cobalt blue', secondaryname:'koboltblå'},
                          {grp:'', name:'realgar', secondaryname:'realgar'},
                          {grp:'', name:'oxide yellow', secondaryname:'oxidgul'},
                          {grp:'', name:'red bole', secondaryname:'bolus rød'},
                          {grp:'', name:'Schweinfürther green', secondaryname:'Schweinfürthergrøn'},
                          {grp:'', name:'massicot', secondaryname:'lead monoxide'},
                          {grp:'', name:'stannic oxide', secondaryname:'tin oxide, tinoxid'},
                          {grp:'', name:'malachite', secondaryname:'malakit'},
                          {grp:'', name:'lapis lazuli', secondaryname:'lapis lazuli'},
                          {grp:'', name:'sandalwood dye', secondaryname:'sandeltræ'},
                          {grp:'', name:'alkanet', secondaryname:'Alkanna tinctoria, dyers bugloss, alkanet root '},
                          {grp:'', name:'kermes', secondaryname:'kermes'},
                          {grp:'', name:'Chinese white', secondaryname:'kinesisk hvid'},
                          {grp:'', name:'cerulean blue', secondaryname:'ceruleanblå'},
                          {grp:'', name:'Prussian blue', secondaryname:'berlinerblå, Paris blue, pariserblå'},
                          {grp:'', name:'graphite', secondaryname:'grønjord '},
                          {grp:'', name:'chromium oxide hydrate', secondaryname:'chromoxidhydrat, viridium'},
                          {grp:'', name:'Indian red', secondaryname:'indisk rød'},
                          {grp:'', name:'burnt sienna', secondaryname:'brændt siena'},
                          {grp:'', name:'raw sienna', secondaryname:'rå siena'},
                          {grp:'', name:'lamp black', secondaryname:'lampesort'},
                          {grp:'', name:'antimony white', secondaryname:'antimonhvid'},
                          {grp:'', name:'strontium white', secondaryname:'strontiumhvid'},
                          {grp:'', name:'tungsten white', secondaryname:'wolfram white, wolframhvid'},
                          {grp:'', name:'carbon black', secondaryname:'soot black, sodsort, vine black, druesort, frankfurtersort'},
                          {grp:'', name:'iron black', secondaryname:'jernsort'},
                          {grp:'', name:'Manganese black', secondaryname:'mangansort'},
                          {grp:'', name:'lead oxide', secondaryname:'blyoxid'},
                          {grp:'', name:'cobalt yellow', secondaryname:'koboltgul'},
                          {grp:'', name:'Mars red', secondaryname:'marsrød'},
                          {grp:'', name:'Florentine brown', secondaryname:'florentinerbrun'},
                          {grp:'', name:'Monastral green', secondaryname:'monastralgrøn'},
                          {grp:'', name:'titanium white', secondaryname:'titanhvid '},
                          {grp:'', name:'chalk', secondaryname:'kridt'},
                          {grp:'', name:'plaster', secondaryname:'gips, gypsum'},
                          {grp:'', name:'kaolin', secondaryname:'kaolin'},
                          {grp:'', name:'talc', secondaryname:'talcum, talkum'},
                          {grp:'', name:'pumice', secondaryname:'pimpsten'},
                          {grp:'', name:'aloe', secondaryname:'aloe '},
                          {grp:'', name:'Dragon\'s blood', secondaryname:'drageblod'},
                          {grp:'', name:'Indian gum resin', secondaryname:'indisk gummiharpiks'},
                          {grp:'', name:'Manganese blue', secondaryname:'manganblå'},
                          {grp:'', name:'Pompeian blue', secondaryname:'pompeijansk blå'},
                          {grp:'', name:'black bole', secondaryname:'bolus sort'},
                          {grp:'', name:'yellow bole', secondaryname:'bolus gul'},
                          {grp:'', name:'Egyptian blue', secondaryname:'ægyptisk blå'},
                          {grp:'', name:'lithopone', secondaryname:'lithopone'},
                          {grp:'', name:'lead-tin yellow', secondaryname:'blytingul'},
                          {grp:'', name:'barium yellow', secondaryname:'bariumgul'},
                          {grp:'', name:'orpiment', secondaryname:'auripigment'},
                          {grp:'', name:'cadmium brown', secondaryname:'cadmium oxide, cadmiumbrun '},
                          {grp:'', name:'green eath', secondaryname:'grønjord'},
                          {grp:'', name:'synthetic verdigris', secondaryname:'syntetisk ir'},
                          {grp:'', name:'bone black', secondaryname:'bensort'},
                          {grp:'', name:'asphalt graphite', secondaryname:'asfalt grafit'},
                          {grp:'', name:'cement black', secondaryname:'cementsort'},
                          {grp:'', name:'ultramarine red', secondaryname:'ultramarinrød'},
                          {grp:'', name:'organic violet', secondaryname:'organisk violet'},
                          {grp:'', name:'Malaga red', secondaryname:'malagarød'},
                          {grp:'', name:'oxide brown', secondaryname:'oxidbrun'},
                          {grp:'', name:'cadmopur yellow', secondaryname:'cadmopurgul'},
                          {grp:'', name:'permanent yellow', secondaryname:'permanentgul'},
                          {grp:'', name:'cement red', secondaryname:'cementrød'},
                          {grp:'', name:'Mars yellow', secondaryname:'marsgul'},
                          {grp:'', name:'Monastral blue', secondaryname:'monastralblå'},
                          {grp:'', name:'ultramarine blue', secondaryname:'ultramarinblå'},
                          {grp:'', name:'organic green', secondaryname:'organisk grøn'},
                          {grp:'', name:'copper acetate', secondaryname:'kobberacetat'},
                          {grp:'', name:'Ferric hydroxide', secondaryname:'iron oxide yellow, jernoxidgul'},
                          {grp:'', name:'oxide red', secondaryname:'oxidrød'},
                          {grp:'', name:'barite', secondaryname:'baryte, tungspat'},
                          {grp:'', name:'slate flour', secondaryname:'skifermel'},
                          {grp:'', name:'chrome orange', secondaryname:'chromorange'},
                          {grp:'', name:'Ceres red', secondaryname:'ceresrød'},
                          {grp:'', name:'iron oxide orange', secondaryname:'jernoxidorange'},
                          {grp:'', name:'Heliogen blue', secondaryname:'heliogenblå'},
                          {grp:'', name:'iron oxide black', secondaryname:'jernoxidsort'},
                          {grp:'', name:'signal red', secondaryname:'signalrød'},
                          {grp:'', name:'maroon', secondaryname:'maron, chestnut'},
                          {grp:'', name:'California yellow', secondaryname:'californiagul'},
                          {grp:'', name:'Sudan red', secondaryname:'sudanrød'},
                          {grp:'', name:'earth colour', secondaryname:'jordfarve'},
                          {grp:'', name:'saffron red', secondaryname:'safranrød'}
                      ]
                    },
                    { type : 'binders',
                      permisssions : 'default',
                      items : [
                          {name: 'casin', secondaryname: 'kasein', grp:''},
                          {name: 'emulsion', secondaryname: 'emulsion', grp:''},
                          {name: 'glue', secondaryname: 'lim', grp:'Glue'},
                          {name: 'animal glue', secondaryname: 'lim animalisk', grp:'Glue'},
                          {name: 'vegetable glue', secondaryname: 'lim vegetabilsk', grp:'Glue'},
                          {name: 'oil', secondaryname: 'olie', grp:'Oil'},
                          {name: 'linseed oil', secondaryname: 'linolie', grp:'Oil'},
                          {name: 'poppy oil', secondaryname: 'valmulie', grp:'Oil'},
                          {name: 'walnut oil', secondaryname: 'valnøddolie', grp:'Oil'},
                          {name: 'resin', secondaryname: 'harpiks', grp:''},
                          {name: 'synthetic', secondaryname: 'syntetisk', grp:''}
                      ]
                    },
                    { type : 'dyes',
                      permisssions : 'default',
                      items : [
                          {name: 'asphalt', secondaryname:'asfalt', grp:''},
                          {name: 'indigo', secondaryname:'indigo', grp:''},
                          {name: 'unknown organic brown', secondaryname:'brun organisk - ubestemt', grp:'Organic brown'},
                          {name: 'brazilwood', secondaryname:'brasiltræ', grp:'Organic red'},
                          {name: 'cocheneal', secondaryname:'cochenille', grp:'Organic red'},
                          {name: 'krap', secondaryname:'krap', grp:'Organic red'},
                          {name: 'unknown organic red', secondaryname:'rød organisk - ubestemt', grp:'Organic red'},
                          {name: 'unknown organic yellow', secondaryname:'gul organisk - ubestemt', grp:'Organic yellow'}
                      ]
                    },
                    { type : 'materials',
                      permisssions : 'default',
                      items : [
                          {name: 'glass', secondaryname:'glas', grp:''},
                          {name: 'bisque', secondaryname:'biskuit', grp:'Ceramical'},
                          {name: 'chamotte', secondaryname:'chamotte', grp:'Ceramical'},
                          {name: 'earthenware', secondaryname:'brændt ler', grp:'Ceramical'},
                          {name: 'faience', secondaryname:'fajance', grp:'Ceramical'},
                          {name: 'pipeclay', secondaryname:'pipeler', grp:'Ceramical'},
                          {name: 'plastiline', secondaryname:'plastilin', grp:'Ceramical'},
                          {name: 'porcelain', secondaryname:'porcelæn', grp:'Ceramical'},
                          {name: 'raku', secondaryname:'raku', grp:'Ceramical'},
                          {name: 'roche céramique', secondaryname:'roche céramique', grp:'Ceramical'},
                          {name: 'stoneware', secondaryname:'stentøj', grp:'Ceramical'},
                          {name: 'terra-cotta', secondaryname:'terrracotta', grp:'Ceramical'},
                          {name: 'unfired clay', secondaryname:'ubrændt ler', grp:'Ceramical'},
                          {name: 'canvas', secondaryname:'lærred', grp:''},
                          {name: 'aluminum', secondaryname:'aluminium)', grp:'Metals'},
                          {name: 'bronze', secondaryname:'bronze', grp:'Metals'},
                          {name: 'copper', secondaryname:'kobber', grp:'Metals'},
                          {name: 'gold', secondaryname:'guld', grp:'Metals'},
                          {name: 'iron', secondaryname:'jern', grp:'Metals'},
                          {name: 'lead', secondaryname:'bly', grp:'Metals'},
                          {name: 'leaf gold', secondaryname:'bladguld', grp:'Metals'},
                          {name: 'ore', secondaryname:'malm', grp:'Metals'},
                          {name: 'pewter', secondaryname:'tin', grp:'Metals'},
                          {name: 'silver', secondaryname:'sølv', grp:'Metals'},
                          {name: 'tin', secondaryname:'blik', grp:'Metals'},
                          {name: 'zinc', secondaryname:'zink', grp:'Metals'},
                          {name: 'organic material', secondaryname:'organisk materiale', grp:''},
                          {name: 'pigment scraping', secondaryname:'pigmentskrab', grp:''},
                          {name: 'acrylate', secondaryname:'akryl', grp:'Synthetic'},
                          {name: 'glass fibre', secondaryname:'glasfiber', grp:'Synthetic'},
                          {name: 'plastic', secondaryname:'plast', grp:'Synthetic'},
                          {name: 'polyester', secondaryname:'polyester', grp:'Synthetic'},
                          {name: 'polyurethane foam', secondaryname:'polyurethanskum', grp:'Synthetic'},
                          {name: 'polyvinyl chloride', secondaryname:'pvc', grp:'Synthetic'},
                          {name: 'ash', secondaryname:'ask', grp:'Wood'},
                          {name: 'beech', secondaryname:'bøgetræ', grp:'Wood'},
                          {name: 'birch', secondaryname:'birketræ', grp:'Wood'},
                          {name: 'boxwood', secondaryname:'buksbom', grp:'Wood'},
                          {name: 'Brazilian rosewood', secondaryname:'palisander', grp:'Wood'},
                          {name: 'ebony', secondaryname:'ibenholt', grp:'Wood'},
                          {name: 'elm', secondaryname:'elmetræ', grp:'Wood'},
                          {name: 'lime', secondaryname:'lindetræ', grp:'Wood'},
                          {name: 'mable', secondaryname:'ahorn', grp:'Wood'},
                          {name: 'mahogany', secondaryname:'mahogni', grp:'Wood'},
                          {name: 'nut', secondaryname:'nøddetræ', grp:'Wood'},
                          {name: 'oak', secondaryname:'egetræ', grp:'Wood'},
                          {name: 'pine', secondaryname:'fyr/pinjetræ', grp:'Wood'},
                          {name: 'poplar', secondaryname:'poppeltræ', grp:'Wood'},
                          {name: 'sandalwood', secondaryname:'sandeltræ', grp:'Wood'},
                          {name: 'teak', secondaryname:'teaktræ', grp:'Wood'},
                          {name: 'walnut', secondaryname:'valnøddetræ', grp:'Wood'},
                          {name: 'willow', secondaryname:'piletræ', grp:'Wood'}
                      ]
                    },
                    { type : 'layerTypes',
                      permisssions : 'admin',
                      items : [
                          {name: 'Ground', secondaryname:'', grp:''},
                          {name: 'Imprimatura', secondaryname:'', grp:''},
                          {name: 'Paint', secondaryname:'', grp:''},
                          {name: 'Varnish', secondaryname:'', grp:''}
                      ]
                    },
                    { type : 'analysisTypes',
                      permisssions : 'admin',
                      items : [
                          {name: 'Automated thread count'},
                          {name: 'C14'},
                          {name: 'Dendrochronology'},
                          {name: 'FTIR'},
                          {name: 'GC-MS'},
                          {name: 'HPLC'},
                          {name: 'IRR'},
                          {name: 'Microscopy'},
                          {name: 'Other'},
                          {name: 'Photographic'},
                          {name: 'Polar. Micro.'},
                          {name: 'Raman'},
                          {name: 'SEM/EDX'},
                          {name: 'Visual'},
                          {name: 'Weave mapping'},
                          {name: 'Wood identification'},
                          {name: 'X-radiography'},
                          {name: 'XRF'}
                      ]
                    },
                    { type : 'fibreTypes',
                      permisssions : 'admin',
                      items : [
                          {name: 'blend'},
                          {name: 'cellulose (wooden)'},
                          {name: 'cotton'},
                          {name: 'hemp'},
                          {name: 'linen'},
                          {name: 'other'},
                          {name: 'synthetic'}
                      ]
                    },
                    { type : 'fibreGlueTypes',
                      permisssions : 'admin',
                      items : [
                          {name: 'animal'},
                          {name: 'synthetic'},
                          {name: 'vegetable'}
                      ]
                    },
                    { type : 'sampleOwners',
                      permisssions : 'admin',
                      items : [   
                         {name: 'National Museum of Denmark'},
                         {name: 'School of Conservation'},
                         {name: 'Statens Museum for Kunst (SMK)'}
                      ]
                    },
                    { type : 'sampleTypes',
                      permisssions : 'admin',
                      items : [
                         {id: 'fibre', name: 'Fibre(paper)', grp:'Physical samples'},
                         {id: 'material', name: 'Material Sample', grp:'Physical samples'},
                         {id: 'paint', name: 'Paint Cross Section', grp:'Physical samples'},
                         {id: 'pigment', name: 'Pigment', grp:'Physical samples'},
                         {id: 'stretcher', name: 'Stretcher/Strainer', grp:'Physical samples'},
                         {id: 'noninvasive', name: 'Non-invasive analysis (no sample)', grp:'Non invasive methods'}
                      ]
                    },
                    { type : 'mediaTypes',
                      permisssions : 'admin',
                      items : [  
                         {name: 'black-and-white negative film', grp:''},
                         {name: 'dias', grp:''},
                         {name: 'analogue IR film', grp:'IR'},
                         {name: 'Digital Artist', grp:'IR'},
                         {name: 'Digital Osiris', grp:'IR'},
                         {name: 'IR vidicon ', grp:'IR'}
                      ]
                    },
                    { type : 'mediaFilms',
                      permisssions : 'admin',
                      items : [ 
                         {name: 'Dowie'},
                         {name: 'EPD120'},
                         {name: 'FP4'},
                         {name: 'FP special'},
                         {name: 'HP3'},
                         {name: 'IR-HS'},
                         {name: 'Kodak IR-ER'},
                         {name: 'Kodak IR.HS4143'}
                      ]
                    },
                    { type : 'mediaFormats',
                      permisssions : 'admin',
                      items : [ 
                         {name: '4 x 4'},
                         {name: '4 x 5'},
                         {name: '6 x 6'},
                         {name: '24 x 36'}
                      ]
                    },
                    { type : 'mediaFilters',
                      permisssions : 'admin',
                      items : [ 
                         {name: 'Kodak Wratten 2B'},
                         {name: 'Kodak Wratten 2E'},
                         {name: 'Kodak Wratten 87'},
                         {name: 'Kodak Wratten 87C'},
                         {name: 'Kodak Wratten 88A'},
                         {name: 'polarization filter'},
                         {name: 'Schott UG-12'}
                      ]
                    },
                    { type : 'mediaLightings',
                      permisssions : 'admin',
                      items : [ 
                         {name: 'natural'},
                         {name: 'regular'},
                         {name: 'side light'},
                         {name: 'sodium light'},
                         {name: 'symmetrical light'},
                         {name: 'tangential light'},
                         {name: 'UV flourescence'},
                         {name: 'UV reflected'}
                      ]
                    },
                    { type : 'mediaScopes',
                      permisssions : 'admin',
                      items : [ 
                         {name: 'back'},
                         {name: 'detail'},
                         {name: 'front'},
                         {name: 'total'}
                      ]
                    },
                    { type : 'xrayTypes',
                      permisssions : 'admin',
                      items : [ 
                         {name: 'analogue'},
                         {name: 'digital'},
                         {name: 'scan'}
                      ]
                    },
                    { type : 'xrayFilmTypes',
                      permisssions : 'admin',
                      items : [ 
                         {name: '30 x 40 cm'},
                         {name: 'Repro film'}
                      ]
                    },
                    { type : 'xrayFilters',
                      permisssions : 'admin',
                      items : [ 
                         {name: 'aluminium'},
                         {name: 'iron'},
                         {name: 'copper'}
                      ]
                    },
                    { type : 'stretcherConditions',
                      permisssions : 'admin',
                      items : [ 
                         {name: 'complete', secondaryname: 'komplet'},
                         {name: 'fragment', secondaryname: 'fragment'}
                      ]
                    },
                    { type : 'stretcherTypes',
                      permisssions : 'admin',
                      items : [
                         {name: 'strainer', secondaryname: 'spændramme'},
                         {name: 'stretcher', secondaryname: 'kileramme'},
                         {name: 'with horizontal cross bar', secondaryname: 'med tværsprosse'},
                         {name: 'with intersecting cross bars', secondaryname: 'med kryds'},
                         {name: 'with double intersecting cross bars', secondaryname: 'med dobbelt kryds'}
                      ]
                    },
                    { type : 'stretcherJointTechniques',
                      permisssions : 'admin',
                      items : [
                         {name: 'bridle joint', secondaryname: 'slids'},
                         {name: 'mitered bridle joint', secondaryname: 'slids med gering'},
                         {name: 'lap joint', secondaryname: 'bladsamling'},
                         {name: 'pinned', secondaryname: 'med dyveler'},
                         {name: 'with reinforcement', secondaryname: 'med forstærkningsplade'},
                         {name: 'other', secondaryname: 'anden'}
                      ]
                    },
                    { type : 'stretcherMaterialTypes',
                      permisssions : 'admin',
                      items : [
                         {name: 'hardwood', secondaryname: 'løvtræ'},
                         {name: 'softwood ', secondaryname: 'nåletræ'}
                      ]
                    },
                    { type : 'pigmentForms',
                      permisssions : 'admin',
                      items : [ 
                         {grp:'', name:'powder', secondaryname:'pulver'},
                         {grp:'', name:'chunk(s)', secondaryname:'stykke'},
                         {grp:'', name:'rock(s)', secondaryname:'sten'},
                         {grp:'', name:'crystal(s)', secondaryname:'krystal'},
                         {grp:'', name:'small chips', secondaryname:'flager'},
                         {grp:'', name:'bound to textile', secondaryname:'tekstil'}
                      ]
                    },
                    { type : 'pigmentContainers',
                      permisssions : 'admin',
                      items : [
                         {grp:'', name:'plastic container', secondaryname:'plastikbeholder'},
                         {grp:'', name:'small bottle', secondaryname:'lille flaske'},
                         {grp:'', name:'original container', secondaryname:'originalemballage'},
                         {grp:'', name:'glass jar', secondaryname:'glasbeholder'}
                      ]
                    }
                ];
    }
}